BASE_FACTORS = {  # commented the ones in other dicts
    "sex": 31,
    "Ethnic background": 21000,
    "Age when attended assessment centre": 21003,
    "Systolic blood pressure, manual reading": 93,
    "Systolic blood pressure, automated reading": 4080,
}

POLYGENIC_RISK_SCORES = {  # 0
    "Standard PRS for age at menopause (AAM)": 26202,
    "Standard PRS for age-related macular degeneration (AMD)": 26204,
    "Standard PRS for alzheimer's disease (AD)": 26206,
    "Standard PRS for asthma (AST)": 26210,
    "Standard PRS for atrial fibrillation (AF)": 26212,
    "Standard PRS for bipolar disorder (BD)": 26214,
    "Standard PRS for body mass index (BMI)": 26216,
    "Standard PRS for bowel cancer (CRC)": 26218,
    "Standard PRS for breast cancer (BC)": 26220,
    "Standard PRS for cardiovascular disease (CVD)": 26223,
    "Standard PRS for coeliac disease (CED)": 26225,
    "Standard PRS for coronary artery disease (CAD)": 26227,
    "Standard PRS for crohn's disease (CD)": 26229,
    "Standard PRS for epithelial ovarian cancer (EOC)": 26232,
    "Standard PRS for estimated bone mineral density t-score (EBMDT)": 26234,
    "Standard PRS for glycated haemoglobin (HBA1C_DF)": 26238,
    "Standard PRS for height (HEIGHT)": 26240,
    "Standard PRS for high density lipoprotein cholesterol (HDL)": 26242,
    "Standard PRS for hypertension (HT)": 26244,
    "Standard PRS for intraocular pressure (IOP)": 26246,
    "Standard PRS for ischaemic stroke (ISS)": 26248,
    "Standard PRS for low density lipoprotein cholesterol (LDL_SF)": 26250,
    "Standard PRS for melanoma (MEL)": 26252,
    "Standard PRS for multiple sclerosis (MS)": 26254,
    "Standard PRS for osteoporosis (OP)": 26258,
    "Standard PRS for parkinson's disease (PD)": 26260,
    "Standard PRS for primary open angle glaucoma (POAG)": 26265,
    "Standard PRS for prostate cancer (PC)": 26267,
    "Standard PRS for psoriasis (PSO)": 26269,
    "Standard PRS for rheumatoid arthritis (RA)": 26273,
    "Standard PRS for schizophrenia (SCZ)": 26275,
    "Standard PRS for systemic lupus erythematosus (SLE)": 26278,
    "Standard PRS for type 1 diabetes (T1D)": 26283,
    "Standard PRS for type 2 diabetes (T2D)": 26285,
    "Standard PRS for ulcerative colitis (UC)": 26287,
    "Standard PRS for venous thromboembolic disease (VTE)": 26289,
}

MEDICAL_HISTORY = {
    "Overall health rating": 2178,
    "Long-standing illness, disability or infirmity": 2188,
    "Weight change compared with 1 year ago": 2306,
    "Other serious medical condition/disability diagnosed by doctor": 2473,
    "Ever had bowel cancer screening": 2345,
    "Most recent bowel cancer screening": 2355,
    "Falls in the last year": 2296,
    "Had major operations": 2415,
    "Wheeze or whistling in the chest in last year": 2316,
    "Fractured/broken bones in last 5 years": 2463,
    "Taking other prescription medications": 2492,
    "Had other major operations": 2844,
    "Age high blood pressure diagnosed": 2966,
    "Fracture resulting from simple fall": 3005,
    "Age hay fever, rhinitis or eczema diagnosed": 3761,
    "Age asthma diagnosed": 3786,
    "Age emphysema/chronic bronchitis diagnosed": 3992,
    "Age deep-vein thrombosis (DVT, blood clot in leg) diagnosed": 4012,
    "Age pulmonary embolism (blood clot in lung) diagnosed": 4022,
    "Gestational diabetes only": 4041,
    "Shortness of breath walking on level ground": 4717,
}

BLOOD_SAMPLES = {
    "1gG antigen for Herpes Simplex virus-1": 23000,
    "White blood cell (leukocyte) count": 30000,
    "Red blood cell (erythrocyte) count": 30010,
    "Haemoglobin concentration": 30020,
    "Haematocrit percentage": 30030,
    "Mean corpuscular volume": 30040,
    "Mean corpuscular haemoglobin": 30050,
    "White blood cell (leukocyte) count": 30060,
    "Mean corpuscular haemoglobin concentration": 30070,
    "Platelet count": 30080,
    "Platelet crit": 30090,
    "Mean platelet (thrombocyte) volume": 30100,
    "Platelet distribution width": 30110,
    "Lymphocyte count": 30120,
    "Monocyte count": 30130,
    "Neutrophill count": 30140,
    "Eosinophill count": 30150,
    "Basophill count": 30160,
    "Albumin": 30600,
    "Alkaline phosphatase": 30610,
    "Alanine aminotransferase": 30620,
    "Apolipoprotein A": 30630,
    "Apolipoprotein B": 30640,
    "Aspartate aminotransferase": 30650,
    "Direct bilirubin": 30660,
    "Urea": 30670,
    "Calcium": 30680,
    "Cholesterol": 30690,
    "Creatinine": 30700,
    "C-reactive protein": 30710,
    "Cystatin C": 30720,
    "Gamma glutamyltransferase": 30730,
    "Glucose": 30740,
    "Glycated haemoglobin (HbA1c)": 30750,
    "HDL cholesterol": 30760,
    "IGF-1": 30770,
    "LDL direct": 30780,
    "Lipoprotein A": 30790,
    "Phosphate": 30810,
    "Total bilirubin": 30840,
    "Total protein": 30860,
    "Triglycerides": 30870,
    "Urate": 30880,
    "Vitamin D": 30890,
}

FAMILY_HISTORY = {
    "Father's age": 2946,
    "Father's age at death": 1807,
    "Mother's age": 1845,
    "Mother's age at death": 3526,
    "Non-accidental death in close genetic family": 4501,
    "Illnesses of father": 20107,
    "Illnesses of mother": 20110,
    "Illnesses of siblings": 20111,
    # "Illnesses of adopted father": 20112,  # ???
    # "Illnesses of adopted mother": 20113,  # ???
    # "Illnesses of adopted siblings": 20114,  # ???
}  # 13 = prostate cancer, 5 = breast cancer

SOCIODEMOGRAPHIC = {
    "Type of accommodation lived in": 670,
    "Number in household": 709,
    "Number of vehicles in household": 728,
    "Average total household income before tax": 738,
    "Length of working week for main job": 767,
    "Transport type for commuting to job workplace": 6143,
    "Frequency of travelling from home to job workplace": 777,
    "Distance between home and job workplace": 796,
    "Job involves mainly walking or standing": 806,
    "Job involves heavy manual or physical work": 816,
    "Job involves shift work": 826,
    "Job involves night shift work": 3426,
    "Age completed full time education": 845,
    "Private healthcare": 4674,
    "Qualifications": 6138,
    "Current employment status - corrected": 20119,
}

LIFESTYLE_ENVIRONMENT = {
    "Number of days/week walked 10+ minutes": 864,
    "Duration of walks": 874,
    "Number of days/week of moderate physical activity 10+ minutes": 884,
    "Duration of moderate activity": 894,
    "Number of days/week of vigorous physical activity 10+ minutes": 904,
    "Duration of vigorous activity": 914,
    "Usual walking pace": 924,
    "Frequency of stair climbing in last 4 weeks": 943,
    "Frequency of walking for pleasure in last 4 weeks": 971,
    "Duration walking for pleasure": 981,
    "Frequency of strenuous sports in last 4 weeks": 991,
    "Duration of strenuous sports": 1001,
    "Frequency of light DIY in last 4 weeks": 1011,
    "Duration of light DIY": 1021,
    "Time spent watching television (TV)": 1070,
    "Time spent using computer": 1080,
    "Time spent driving": 1090,
    "Sleep duration": 1160,
    "Nap during day": 1190,
    "Sleeplessness / insomnia": 1200,
    "Snoring": 1210,
    "Daytime dozing / sleeping": 1220,
    "Current tobacco smoking": 1239,
    "Past tobacco smoking": 1249,
    "Smoking/smokers in household": 1259,
    "Exposure to tobacco smoke at home": 1269,
    "Exposure to tobacco smoke outside home": 1279,
    "Alcohol intake frequency": 1558,
    "Average weekly red wine intake": 1568,
    "Average weekly champagne plus white wine intake": 1578,
    "Average weekly beer plus cider intake": 1588,
    "Average weekly spirits intake": 1598,
    "Average weekly fortified wine intake": 1608,
    "Alcohol usually taken with meals": 1618,
    "Alcohol intake versus 10 years previously": 1628,
    "Frequency of heavy DIY in last 4 weeks": 2624,
    "Duration of heavy DIY": 2634,
    "Frequency of other exercises in last 4 weeks": 3637,
    "Duration of other exercises": 3647,
    "Smoking status": 20116,
    "Alcohol drinker status": 20117,
    "Ever smoked": 20160,
    "Pack years of smoking": 20161,
    "Pack years adult smoking as proportion of life span exposed to smoking": 20162,
    "At or above moderate/vigorous recommendation": 22035,
    "At or above moderate/vigorous/walking recommendation": 22036,
    "MET minutes per week for walking": 22037,
    "MET minutes per week for moderate activity": 22038,
    "MET minutes per week for vigorous activity": 22039,
}

PHYSICAL_MEASUREMENTS = {
    # "Forced vital capacity (FVC)": 3062,
    # "Forced expiratory volume in 1-second (FEV1)": 3063,
    "Peak expiratory flow (PEF)": 3064,
    "Pulse rate": 4194,
    "Pulse wave reflection index": 4195,
    "Pulse wave peak to peak time": 4196,
    "Position of the pulse wave peak": 4198,
    "Position of pulse wave notch": 4199,
    "Position of the shoulder on the pulse waveform": 4200,
    "Absence of notch position in the pulse waveform": 4204,
    "Pulse wave velocity (manual entry)": 4207,
    # "ECG, heart rate": 5983,  # too many
    "Chest pain felt during physical activity": 6015,
    "Chest pain felt outside physical activity": 6016,
    "Able to walk or cycle unaided for 10 minutes": 6017,
    "Maximum workload during fitness test": 6032,
    "Maximum heart rate during fitness test": 6033,
    "Target heart rate achieved": 6034,
    "Duration of fitness test": 6039,
    "Forced expiratory volume in 1-second (FEV1), Best measure": 20150,
    "Forced expiratory volume in 1-second (FEV1) Z-score": 20256,
    "Forced vital capacity (FVC), Best measure": 20151,
    "Forced vital capacity (FVC) Z-score": 20257,
    "FEV1/ FVC ratio Z-score": 20258,
    "Body mass index (BMI)": 21001,
    "Pulse wave Arterial Stiffness index": 21021,
    "Weight": 23098,
    "Body fat percentage": 23099,
    "Whole body fat mass": 23100,
    "Whole body fat-free mass": 23101,
    "Whole body water mass": 23102,
}

URINE_ASSAYS = {
    "Microalbumin in urine": 30500,
    "Microalbumin in urine result flag": 30505,
    "Creatinine (enzymatic) in urine": 30510,
    "Potassium in urine": 30520,
    "Potassium in urine result flag": 30525,
    "Sodium in urine": 30530,
    "Sodium in urine result flag": 30535,
}

FEMALE_SPECIFIC_FACTORS = {
    "Ever had breast cancer screening / mammogram": 2674,
    "Years since last breast cancer screening / mammogram": 2684,
    "Ever had cervical smear test": 2694,
    "Years since last cervical smear test": 2704,
    "Age when periods started (menarche)": 2714,
    "Had menopause": 2724,
    "Age at menopause (last menstrual period)": 3581,
    "Time since last menstrual period": 3700,
    "Length of menstrual cycle": 3710,
    "Menstruating today": 3720,
    "Number of live births": 2734,
    "Birth weight of first child": 2744,
    "Age of primiparous women at birth of child": 3872,
    "Age at first live birth": 2754,
    "Age at last live birth": 2764,
    "Ever had stillbirth, spontaneous miscarriage or termination": 2774,
    "Number of stillbirths": 3829,
    "Number of spontaneous miscarriages": 3839,
    "Number of pregnancy terminations": 3849,
    "Ever taken oral contraceptive pill": 2784,
    "Type of progestan-only oral contraceptive used (pilot)": 10132,
    "Age started oral contraceptive pill": 2794,
    "Age when last used oral contraceptive pill": 2804,
    "Ever used hormone-replacement therapy (HRT)": 2814,
    "Age started hormone-replacement therapy (HRT)": 3536,
    "Age last used hormone-replacement therapy (HRT)": 3546,
    "Ever had hysterectomy (womb removed)": 3591,
    "Age at hysterectomy": 2824,
    "Bilateral oophorectomy (both ovaries removed)": 2834,
    "Age at bilateral oophorectomy (both ovaries removed)": 3882,
}

MALE_SPECIFIC_FACTORS = {
    "Ever had prostate specific antigen (PSA) test": 2365,
    "Time since last prostate specific antigen (PSA) test": 3809,
    "Relative age of first facial hair": 2375,
    "Relative age voice broke": 2385,
    "Hair/balding pattern": 2395,
    "Number of children fathered": 2405,
}

DIAGNOSES = {
    "sex": 31,
    "Diagnoses - ICD10": 41270,
    "Date of first in-patient diagnosis - ICD10": 41280,
    "Type of cancer: ICD10": 40006,
    "Date of cancer diagnosis": 40005,
    "Date of attending assessment centre": 53,
}

CANCER = {
    "Diagnoses - ICD10": 41270,
    "Date of first in-patient diagnosis - ICD10": 41280,
    "Type of cancer: ICD10": 40006,
    "Date of cancer diagnosis": 40005,
    "Date of attending assessment centre": 53,
}

DIABETES = {
    "Diagnoses - ICD10": 41270,
    "Date of first in-patient diagnosis - ICD10": 41280,
    "Date of attending assessment centre": 53,
}

MYELOMA = {
    "Diagnoses - ICD10": 41270,
    "Date of first in-patient diagnosis - ICD10": 41280,
    "Date of attending assessment centre": 53,
}

COPD = {
    "Diagnoses - ICD10": 41270,
    "Date of first in-patient diagnosis - ICD10": 41280,
    "Date of attending assessment centre": 53,
}

MERGED_ATTRIBUTES = {
    **BASE_FACTORS,
    **POLYGENIC_RISK_SCORES,
    **MEDICAL_HISTORY,
    **BLOOD_SAMPLES,
    **FAMILY_HISTORY,
    # **SOCIODEMOGRAPHIC,
    **LIFESTYLE_ENVIRONMENT,
    **PHYSICAL_MEASUREMENTS,
    **URINE_ASSAYS,
    **FEMALE_SPECIFIC_FACTORS,
    **MALE_SPECIFIC_FACTORS,
}

ATTRIBUTES = list(MERGED_ATTRIBUTES.keys())
