basic_binary = {
    1: "Yes",
    0: "No",
    -1: "Do not know",
    -3: "Prefer not to answer",
}

LABEL_MAPPING = {
    "Diabetes": {1: "Yes", 0: "No", -1: "Do not know", -3: "Prefer not to answer"},
    "Father still alive": basic_binary,
    "Mother still alive": basic_binary,
    "Non-accidental death in close genetic family": basic_binary,
    "Oral contraceptive pill or minipill": {1: "Yes", 0: "No"},
    "Hormone replacement therapy": {1: "Yes", 0: "No"},
    "Insulin": {1: "Yes", 0: "No"},
    "Blood pressure medication": {1: "Yes", 0: "No"},
    "Cholesterol lowering medication": {1: "Yes", 0: "No"},
    "Father has hip fracture": {1: "Yes", 0: "No"},
    "Father has prostate cancer": {1: "Yes", 0: "No"},
    "Father has severe depression": {1: "Yes", 0: "No"},
    "Father has parkinson's disease": {1: "Yes", 0: "No"},
    "Father has alzheimer's disease/dementia": {1: "Yes", 0: "No"},
    "Father has diabetes": {1: "Yes", 0: "No"},
    "Father has high blood pressure": {1: "Yes", 0: "No"},
    "Father has chronic bronchitis/emphysema": {1: "Yes", 0: "No"},
    "Father has breast cancer": {1: "Yes", 0: "No"},
    "Father has bowel cancer": {1: "Yes", 0: "No"},
    "Father has lung cancer": {1: "Yes", 0: "No"},
    "Father has stroke": {1: "Yes", 0: "No"},
    "Father has heart disease": {1: "Yes", 0: "No"},
    "Mother has hip fracture": {1: "Yes", 0: "No"},
    "Mother has severe depression": {1: "Yes", 0: "No"},
    "Mother has parkinson's disease": {1: "Yes", 0: "No"},
    "Mother has alzheimer's disease/dementia": {1: "Yes", 0: "No"},
    "Mother has diabetes": {1: "Yes", 0: "No"},
    "Mother has high blood pressure": {1: "Yes", 0: "No"},
    "Mother has chronic bronchitis/emphysema": {1: "Yes", 0: "No"},
    "Mother has breast cancer": {1: "Yes", 0: "No"},
    "Mother has bowel cancer": {1: "Yes", 0: "No"},
    "Mother has lung cancer": {1: "Yes", 0: "No"},
    "Mother has stroke": {1: "Yes", 0: "No"},
    "Mother has heart disease": {1: "Yes", 0: "No"},
    "Siblings have hip fracture": {1: "Yes", 0: "No"},
    "Siblings have prostate cancer": {1: "Yes", 0: "No"},
    "Siblings have severe depression": {1: "Yes", 0: "No"},
    "Siblings have parkinson's disease": {1: "Yes", 0: "No"},
    "Siblings have alzheimer's disease/dementia": {1: "Yes", 0: "No"},
    "Siblings have diabetes": {1: "Yes", 0: "No"},
    "Siblings have high blood pressure": {1: "Yes", 0: "No"},
    "Siblings have chronic bronchitis/emphysema": {1: "Yes", 0: "No"},
    "Siblings have breast cancer": {1: "Yes", 0: "No"},
    "Siblings have bowel cancer": {1: "Yes", 0: "No"},
    "Siblings have lung cancer": {1: "Yes", 0: "No"},
    "Siblings have stroke": {1: "Yes", 0: "No"},
    "Siblings have heart disease": {1: "Yes", 0: "No"},
    "Oral contraceptive pill or minipill": {1: "Yes", 0: "No"},
    "Hormone replacement therapy": {1: "Yes", 0: "No"},
    "Insulin": {1: "Yes", 0: "No"},
    "Blood pressure medication": {1: "Yes", 0: "No"},
    "Cholesterol lowering medication": {1: "Yes", 0: "No"},
    "Illnesses of father:": {
        14: "Hip fracture",
        13: "Prostate cancer",
        12: "Severe depression",
        11: "Parkinson's disease",
        10: "Alzheimer's disease/dementia",
        9: "Diabetes",
        8: "High blood pressure",
        6: "Chronic bronchitis/emphysema",
        5: "Breast cancer",
        4: "Bowel cancer",
        3: "Lung cancer",
        2: "Stroke",
        1: "Heart disease",
        -11: "Do not know (group 1)",
        -13: "Prefer not to answer (group 1)",
        -17: "None of the above (group 1)",
        -21: "Do not know (group 2)",
        -23: "Prefer not to answer (group 2)",
        -27: "None of the above (group 2)",
    },
    "Alcohol drinker status": {
        -3: "Prefer not to answer",
        0: "Never",
        1: "Previous",
        2: "Current",
    },
    "Alcohol intake frequency": {
        1: "Daily or almost daily",
        2: "Three or four times a week",
        3: "Once or twice a week",
        4: "One to three times a month",
        5: "Special occasions only",
        6: "Never",
        -3: "Prefer not to answer",
    },
    "Alcohol usually taken with meals": {
        1: "Yes",
        0: "No",
        -6: "It varies",
        -3: "Prefer not to answer",
        -1: "Do not know",
    },
    "Amount of alcohol drunk on a typical drinking day": {
        -818: "Prefer not to answer",
        1: "1 or 2",
        2: "3 or 4",
        3: "5 or 6",
        4: "7, 8, or 9",
        5: "10 or more",
    },
    "Beef intake": {
        0: "Never",
        1: "Less than once a week",
        2: "Once a week",
        3: "2–4 times a week",
        4: "5–6 times a week",
        5: "Once or more daily",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Hormone replacement therapy medication regularly taken": {
        1: "Cholesterol lowering medication",
        2: "Blood pressure medication",
        3: "Insulin",
        4: "Hormone replacement therapy",
        5: "Oral contraceptive pill or minipill",
        -7: "None of the above",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Cholesterol lowering medication regularly taken": {
        1: "Cholesterol lowering medication",
        2: "Blood pressure medication",
        3: "Insulin",
        -7: "None of the above",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Current tobacco smoking": {
        1: "Yes, on most or all days",
        2: "Only occasionally",
        0: "No",
        -3: "Prefer not to answer",
    },
    "Duration of heavy DIY": {
        1: "Less than 15 minutes",
        2: "Between 15 and 30 minutes",
        3: "Between 30 minutes and 1 hour",
        4: "Between 1 and 1.5 hours",
        5: "Between 1.5 and 2 hours",
        6: "Between 2 and 3 hours",
        7: "Over 3 hours",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Duration of light DIY": {
        1: "Less than 15 minutes",
        2: "Between 15 and 30 minutes",
        3: "Between 30 minutes and 1 hour",
        4: "Between 1 and 1.5 hours",
        5: "Between 1.5 and 2 hours",
        6: "Between 2 and 3 hours",
        7: "Over 3 hours",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Duration of other exercises": {
        1: "Less than 15 minutes",
        2: "Between 15 and 30 minutes",
        3: "Between 30 minutes and 1 hour",
        4: "Between 1 and 1.5 hours",
        5: "Between 1.5 and 2 hours",
        6: "Between 2 and 3 hours",
        7: "Over 3 hours",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Duration of strenuous sports": {
        1: "Less than 15 minutes",
        2: "Between 15 and 30 minutes",
        3: "Between 30 minutes and 1 hour",
        4: "Between 1 and 1.5 hours",
        5: "Between 1.5 and 2 hours",
        6: "Between 2 and 3 hours",
        7: "Over 3 hours",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Duration walking for pleasure": {
        1: "Less than 15 minutes",
        2: "Between 15 and 30 minutes",
        3: "Between 30 minutes and 1 hour",
        4: "Between 1 and 1.5 hours",
        5: "Between 1.5 and 2 hours",
        6: "Between 2 and 3 hours",
        7: "Over 3 hours",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Ever smoked": {0: "No", 1: "Yes"},
    "Falls in the last year": {
        1: "No falls",
        2: "Only one fall",
        3: "More than one fall",
        -3: "Prefer not to answer",
    },
    "Frequency of consuming six or more units of alcohol": {
        -818: "Prefer not to answer",
        1: "Never",
        2: "Less than monthly",
        3: "Monthly",
        4: "Weekly",
        5: "Daily or almost daily",
    },
    "Frequency of drinking alcohol": {
        -818: "Prefer not to answer",
        0: "Never",
        1: "Monthly or less",
        2: "2 to 4 times a month",
        3: "2 to 3 times a week",
        4: "4 or more times a week",
    },
    "Frequency of heavy DIY in last 4 weeks": {
        1: "Once in the last 4 weeks",
        2: "2–3 times in the last 4 weeks",
        3: "Once a week",
        4: "2–3 times a week",
        5: "4–5 times a week",
        6: "Every day",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Frequency of other exercises in last 4 weeks": {
        1: "Once in the last 4 weeks",
        2: "2–3 times in the last 4 weeks",
        3: "Once a week",
        4: "2–3 times a week",
        5: "4–5 times a week",
        6: "Every day",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Frequency of stair climbing in last 4 weeks": {
        0: "None",
        1: "1-5 times a day",
        2: "6-10 times a day",
        3: "11-15 times a day",
        4: "16-20 times a day",
        5: "More than 20 times a day",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Frequency of strenuous sports in last 4 weeks": {
        1: "Once in the last 4 weeks",
        2: "2–3 times in the last 4 weeks",
        3: "Once a week",
        4: "2–3 times a week",
        5: "4–5 times a week",
        6: "Every day",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Frequency of walking for pleasure in last 4 weeks": {
        1: "Once in the last 4 weeks",
        2: "2–3 times in the last 4 weeks",
        3: "Once a week",
        4: "2–3 times a week",
        5: "4–5 times a week",
        6: "Every day",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Lamb/mutton intake": {
        0: "Never",
        1: "Less than once a week",
        2: "Once a week",
        3: "2-4 times a week",
        4: "5-6 times a week",
        5: "Once or more daily",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Days/week moderate activity": {
        0: "Not at all",
        1: "1 day a week",
        2: "2 days a week",
        3: "3 days a week",
        4: "4 days a week",
        5: "5 days a week",
        6: "6 days a week",
        7: "7 days a week",
        -3: "Prefer not to answer",
        -1: "Do not know",
    },
    "Days/week vigorous activity": {
        0: "Not at all",
        1: "1 day a week",
        2: "2 days a week",
        3: "3 days a week",
        4: "4 days a week",
        5: "5 days a week",
        6: "6 days a week",
        7: "7 days a week",
        -3: "Prefer not to answer",
        -1: "Do not know",
    },
    "Overall health rating": {
        1: "Excellent",
        2: "Good",
        3: "Fair",
        4: "Poor",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Pace": {0: "No", 1: "Yes"},
    "Past tobacco smoking": {
        1: "Smoked on most or all days",
        2: "Smoked occasionally",
        3: "Just tried once or twice",
        4: "I have never smoked",
        -3: "Prefer not to answer",
    },
    "Pork intake": {
        0: "Never",
        1: "Less than once a week",
        2: "Once a week",
        3: "2-4 times a week",
        4: "5-6 times a week",
        5: "Once or more daily",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Processed meat intake": {
        0: "Never",
        1: "Less than once a week",
        2: "Once a week",
        3: "2-4 times a week",
        4: "5-6 times a week",
        5: "Once or more daily",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Shortness of breath walking on level ground": basic_binary,
    "Sleeplessness / insomnia": {
        1: "Never/rarely",
        2: "Sometimes",
        3: "Usually",
        -3: "Prefer not to answer",
    },
    "Smoking/smokers in household": {
        1: "Yes, one household member smokes",
        2: "Yes, more than one household member smokes",
        0: "No",
        -3: "Prefer not to answer",
    },
    "Tense / highly strung": basic_binary,
    "Usual walking pace": {
        1: "Slow pace",
        2: "Steady average pace",
        3: "Brisk pace",
        -7: "None of the above",
        -3: "Prefer not to answer",
    },
    "Weight change compared with 1 year ago": {
        0: "No - weigh about the same",
        2: "Yes - gained weight",
        3: "Yes - lost weight",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Worrier / anxious feelings": basic_binary,
    "smoking": {
        0: "Never",
        1: "Previous",
        2: "Current",
        4: "Prefer not to answer",
        -3: "Prefer not to answer",
    },
    "sex": {0: "Female", 1: "Male"},
    "Ethnic background": {
        1: "White",
        1001: "British",
        2001: "White and Black Caribbean",
        3001: "Indian",
        4001: "Caribbean",
        2: "Mixed",
        1002: "Irish",
        2002: "White and Black African",
        3002: "Pakistani",
        4002: "African",
        3: "Asian or Asian British",
        1003: "Any other white background",
        2003: "White and Asian",
        3003: "Bangladeshi",
        4003: "Any other Black background",
        4: "Black or Black British",
        1002: "Irish",
        2002: "White and Black African",
        3002: "Pakistani",
        4002: "African",
        3: "Asian or Asian British",
        1003: "Any other white background",
        2003: "White and Asian",
        3003: "Bangladeshi",
        4003: "Any other Black background",
        4: "Black or Black British",
        2004: "Any other mixed background",
        3004: "Any other Asian background",
        5: "Chinese",
        6: "Other ethnic group",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Long-standing illness, disability or infirmity": basic_binary,
    "Cancer diagnosed by doctor": basic_binary,
    "Other serious medical condition/disability diagnosed by doctor": basic_binary,
    "Ever had bowel cancer screening": basic_binary,
    "Had major operations": basic_binary,
    "Diabetes diagnosed by doctor": basic_binary,
    "Wheeze or whistling in the chest in last year": basic_binary,
    "Fractured/broken bones in last 5 years": basic_binary,
    "Taking other prescription medications": basic_binary,
    "Had other major operations": basic_binary,
    "Fracture resulting from simple fall": basic_binary,
    "Gestational diabetes only": {
        1: "Yes",
        0: "No",
        -1: "Do not know",
        -2: "Not applicable",
        -3: "Prefer not to answer",
    },
    "Type of accommodation lived in": {
        1: "A house or bungalow",
        2: "A flat, maisonette or apartment",
        3: "Mobile or temporary structure (i.e. caravan)",
        4: "Sheltered accommodation",
        5: "Care home",
        -7: "None of the above",
        -3: "Prefer not to answer",
    },
    "Average total household income before tax": {
        1: "Less than 18,000",
        2: "18,000 to 30,999",
        3: "31,000 to 51,999",
        4: "52,000 to 100,000",
        5: "Greater than 100,000",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Transport type for commuting to job workplace": {
        1: "Car/motor vehicle",
        2: "Walk",
        3: "Public transport",
        4: "Cycle",
        -7: "None of the above",
        -3: "Prefer not to answer",
    },
    "Job involves mainly walking or standing": {
        1: "Never/rarely",
        2: "Sometimes",
        3: "Usually",
        4: "Always",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Job involves heavy manual or physical work": {
        1: "Never/rarely",
        2: "Sometimes",
        3: "Usually",
        4: "Always",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Job involves shift work": {
        1: "Never/rarely",
        2: "Sometimes",
        3: "Usually",
        4: "Always",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Job involves night shift work": {
        1: "Never/rarely",
        2: "Sometimes",
        3: "Usually",
        4: "Always",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Private healthcare": {
        1: "Yes, all of the time",
        2: "Yes, most of the time",
        3: "Yes, sometimes",
        4: "No, never",
        -1: "Do not know",
        -3: "Prefer not to answer",
    },
    "Qualifications": {
        1: "College or University degree",
        2: "A levels/AS levels or equivalent",
        3: "O levels/GCSEs or equivalent",
        4: "CSEs or equivalent",
        5: "NVQ or HND or HNC or equivalent",
        6: "Other professional qualifications eg: nursing, teaching",
        -7: "None of the above",
        -3: "Prefer not to answer",
    },
    "Current employment status - corrected": {
        1: "In paid employment or self-employed",
        2: "Retired",
        3: "Looking after home and/or family",
        4: "Unable to work because of sickness or disability",
        5: "Unemployed",
        6: "Doing unpaid or voluntary work",
        7: "Full or part-time student",
        -7: "None of the above",
        -3: "Prefer not to answer",
    },
    "Nap during day": {
        1: "Never/rarely",
        2: "Sometimes",
        3: "Usually",
        -3: "Prefer not to answer",
    },
    "Snoring": basic_binary,
}

NUMERICAL_MAPPING = {
    "Alcohol drinker status": {-3: 3, 0: 0, 1: 1, 2: 2},
    "Alcohol intake frequency": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        -3: 0,
    },
    "Alcohol usually taken with meals": {1: 1, 0: 0, -6: 2, -3: 3, -1: 4},
    "Amount of alcohol drunk on a typical drinking day": {
        -818: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        0: 0,  # NaN
    },
    "Beef intake": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, -1: 6, -3: 7},
    "Hormone replacement therapy medication regularly taken": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        -7: 6,
        -1: 0,
        -3: 7,
    },
    "Cholesterol lowering medication regularly taken": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        -7: 4,
        -1: 0,
        -3: 5,
    },
    "Current tobacco smoking": {1: 1, 2: 2, 0: 0, -3: 3},
    "Duration of heavy DIY": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -1: 0,
        -3: 8,
    },
    "Duration of light DIY": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -1: 0,
        -3: 8,
    },
    "Duration of other exercises": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -1: 0,
        -3: 8,
    },
    "Duration of strenuous sports": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -1: 0,
        -3: 8,
    },
    "Duration walking for pleasure": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -1: 0,
        -3: 8,
    },
    "Ever smoked": {0: 0, 1: 1},
    "Falls in the last year": {0: 0, 1: 1, 2: 2, 3: 3, -3: 0},  # NaN
    "Frequency of consuming six or more units of alcohol": {
        0: 0,  # NaN
        -818: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
    },
    "Frequency of drinking alcohol": {
        0: 0,  # NaN
        -818: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
    },
    "Frequency of heavy DIY in last 4 weeks": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        -1: 0,
        -3: 7,
    },
    "Frequency of other exercises in last 4 weeks": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        -1: 0,
        -3: 7,
    },
    "Frequency of stair climbing in last 4 weeks": {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        -1: 6,
        -3: 7,
    },
    "Frequency of strenuous sports in last 4 weeks": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        -1: 0,
        -3: 7,
    },
    "Frequency of walking for pleasure in last 4 weeks": {
        0: 0,  # NaN
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        -1: 0,
        -3: 7,
    },
    "Lamb/mutton intake": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, -1: 6, -3: 7},
    "Days/week moderate activity": {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -3: 8,
        -1: 9,
    },
    "Days/week vigorous activity": {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        -3: 8,
        -1: 9,
    },
    "Overall health rating": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, -1: 0, -3: 5},  # NaN
    "Pace": {0: 0, 1: 1},
    "Past tobacco smoking": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, -3: 0},  # NaN
    "Pork intake": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, -1: 6, -3: 7},
    "Processed meat intake": {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, -1: 6, -3: 7},
    "Shortness of breath walking on level ground": {1: 1, 0: 0, -1: 2, -3: 3},
    "Sleeplessness / insomnia": {0: 0, 1: 1, 2: 2, 3: 3, -3: 0},  # NaN
    "Smoking/smokers in household": {1: 1, 2: 2, 0: 0, -3: 3},
    "Tense / highly strung": {1: 1, 0: 0, -1: 2, -3: 3},
    "Usual walking pace": {0: 0, 1: 1, 2: 2, 3: 3, -7: 4, -3: 0},  # NaN
    "Weight change compared with 1 year ago": {0: 0, 2: 1, 3: 2, -1: 3, -3: 4},
    "Worrier / anxious feelings": {1: 1, 0: 0, -1: 2, -3: 3},
    "smoking": {0: 0, 1: 1, 2: 2, 4: 3, -3: 3},
    "sex": {0: 0, 1: 1},
}
